catalog:
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plus: latest
    vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogs:
    cli:
        "@clack/prompts": 1.2.0
        "@std/front-matter": jsr:1.0.9
        arktype: 2.2.0
        human-id: 4.1.3
        picocolors: 1.1.1

    dev:
        "@types/node": 25.6.0
        typescript: 6.0.3

overrides:
    vite: "catalog:"
    vitest: "catalog:"

peerDependencyRules:
    allowAny:
        - vite
        - vitest
    allowedVersions:
        vite: "*"
        vitest: "*"
